### ISSUE TITLE
Reference to SCPI

### ISSUE THREAD

**Issue by Fraunhofer-IIS** [python-ivi/python-ivi#34]
I'm missing a reference to SCPI and how it relates to the rest of the standards in the README.

Are the commands that are defined in the "base" instruments really so instrument specific?

**Comment by alexforencich** [comment]
They are.  It can be extremely annoying.  However, some instruments are more similar than others for whatever reason.  Most of the power supplies, for example, have very similar protocols.  So the SCPI standards in python-ivi provide a repository for implementations that are compatible (possibly with some minor variations) across multiple devices.  For other instruments, there can be rather complex mappings that relate sets of parameters to other sets of parameters.  Probably the worst offender would be oscilloscope triggering settings.

**Comment by willzeng** [comment]
Should this be closed or does something need to be added into the wiki or the README?

**Comment by Fraunhofer-IIS** [comment]
I leave those links as reference:
 - http://www.ivifoundation.org/specifications/
 - http://www.ivifoundation.org/scpi/
