### ISSUE TITLE
dcpwr.py --> doesn't accept negative voltage 

### ISSUE THREAD

**Issue by Murdock86** [python-ivi/python-ivi#46]
I was using this smart tool to control Agilent E3631A  power unit which supports one channel with negative voltage.
It rose a ivi.OutOfRangeException() since it only accepts values bigger than 0 up to the maximum voltage. (dcpwr.py line 265/266)
One should add an option for negative voltage values

**Comment by alexforencich** [comment]
Hmm.  This worked when I originally wrote the driver, but it's possible
that it got refactored and something broke.  I will debug this in the
next couple of days and get it fixed. 

Alex Forencich

**Comment by Murdock86** [comment]
Dear Alex,

I’ve been using Python since a few weeks so I’m still a noob. I guess you find a more elegant way to solve it:

    def _set_output_voltage_level(self, index, value):
        index = ivi.get_index(self._output_name, index)
        value = float(value)
        if self._output_spec[index]['voltage_max'] >= 0:
            if value > self._output_spec[index]['voltage_max']:
                raise ivi.OutOfRangeException()
            if not self._driver_operation_simulate:
                if self._output_count > 1:
                    self._write("instrument:nselect %d" % (index+1))
                self._write("source:voltage:level %.6f" % value)
            self._output_voltage_level[index] = value
            self._set_cache_valid(index=index)
        else:
            if value < self._output_spec[index]['voltage_max']:
               raise ivi.OutOfRangeException()
            if not self._driver_operation_simulate:
                if self._output_count > 1:
                    self._write("instrument:nselect %d" % (index+1))
                self._write("source:voltage:level %.6f" % value)
            self._output_voltage_level[index] = value
            self._set_cache_valid(index=index)
I haven’t checked if this problem shows up again. Anyway thx for the lib!

Best

Mike



Von: Alex Forencich [mailto:notifications@github.com]
Gesendet: Mittwoch, 9. März 2016 23:16
An: python-ivi/python-ivi
Cc: Mettraux, Michael
Betreff: Re: [python-ivi] dcpwr.py --> doesn't accept negative voltage (#46)

Hmm. This worked when I originally wrote the driver, but it's possible
that it got refactored and something broke. I will debug this in the
next couple of days and get it fixed.

Alex Forencich

**Comment by alexforencich** [comment]
Yeah, I just took a look at dcpwr.py, and there are a bunch of cases
where negative voltage ranges will cause trouble.  I will look in to
fixing it properly there. 

Alex Forencich

**Comment by alexforencich** [comment]
Pushed some updates to my fork; try it out and let me know if it works
for you.

Alex Forencich

**Comment by Murdock86** [comment]
Yes it works!


Von: Alex Forencich [mailto:notifications@github.com]
Gesendet: Donnerstag, 10. März 2016 09:02
An: python-ivi/python-ivi
Cc: Mettraux, Michael
Betreff: Re: [python-ivi] dcpwr.py --> doesn't accept negative voltage (#46)

Pushed some updates to my fork; try it out and let me know if it works
for you.

Alex Forencich
