### ISSUE TITLE
Interface between ivi and PyVisa

### ISSUE THREAD

**Issue by JacobEFO** [python-ivi/python-ivi#69]
Dear developers

I am currently interfacing with lab equipment using both ivi (for my Lecroy scope) and also Pyvisa for my Rigol DP832 and Tektronix AFG3102C. 
I was wondering, if I could in any way use IVI for my Rigol DP832 and Tektronix AFG3102C as well, I'd gladly write it myself, but I am not sure, how I pass on the commands to the equipment.

Currently I use PyVisa to create an instrument object and simply call:

> instr.write(command)

How would I accomplish the same in ivi?

**Comment by alexforencich** [comment]
You should be able to do 

    instr._write("some command")

and

    instr._ask("some query?")
